# Generated by Django 5.0.4 on 2024-04-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hospital_center",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=255)),
                ("Town", models.CharField(max_length=100)),
                ("Region", models.CharField(max_length=100)),
                ("District", models.CharField(max_length=100)),
            ],
        ),
    ]
